### ISSUE TITLE
Does not work on Windows

### ISSUE THREAD

**Issue by alessioalex** [hij1nx/pxx#2]
``` bash
$ pxx

Password:
fs.js:427
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory 'c:\dev\stdin'
    at Object.fs.openSync (fs.js:427:18)
    at module.exports (c:\Users\avladutu\AppData\Roaming\npm\node_modules\pxx\node_modules\prompt-sync\index.j
s:7:15)
    at openEncrypted (c:\Users\avladutu\AppData\Roaming\npm\node_modules\pxx\index.js:102:18)
    at Object.<anonymous> (c:\Users\avladutu\AppData\Roaming\npm\node_modules\pxx\index.js:136:2)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
```

**Comment by alessioalex** [comment]
So the error is coming from `prompt-sync` -> https://github.com/hij1nx/prompt-sync/blob/master/index.js#L7

**Comment by heapwolf** [comment]
@alessioalex :+1: added you as a collaborator!

**Comment by alessioalex** [comment]
Awesome, thank you!

P.S. I totally wanted to make this exact module at some point in time, happy to see your work here!
